version: 0.1

phases:
  install:
    commands:
      #aws code build use ubuntu environement
      # Download and Install NodeJS 12
      - echo installing nodejs...
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt-get install -y nodejs

      # Install http drivers for node
      - echo Installing source NPM dependencies...
      - sudo apt-get update -y
      - sudo apt-get install -y apt-transport-https
  pre_build:
    commands:
      - echo installing dependencies...
      - npm i -g @angular/cli@10
      - npm install
  build:
    commands:
      # - echo testing...
      # - echo building...
      # - npm run build:prod
      - ng build --configuration=prod
  post_build:
    commands:
      - mv appspec.yml ./dist/ha-marketplace-app
      - mv scripts ./dist/ha-marketplace-app
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist/ha-marketplace-app
